### PR TITLE
Update deps, formatting and fix type issues

### LINKED ISSUE #2: Make segments customisable in CMS

### PR DESCRIPTION
**Pull request by CallumHoward**
Updates some dependencies, improve formatting and fix type checks.

Can now run `pnpm -F web check` and it passes

### CODE REVIEW

File: apps/studio/schemas/testimonial.ts [hunk 1]
```diff
@@ -35,7 +35,7 @@ export default defineType({
       title: "Rating 0-5",
       type: "number",
       initialValue: 5,
-      validation: (Rule) => Rule.min(0).max(5).integer(),
+      validation: (Rule) => Rule.min(0).max(5).integer().required(),
```
Comment (CallumHoward) [inline apps/studio/schemas/testimonial.ts:38]: I can't remember if this was needed, I might have added it just to test

File: apps/web/src/components/StarRating.svelte [hunk 2]
```diff
@@ -1,21 +1,21 @@
...
+          name="rating"
+          class="mask mask-star cursor-auto bg-orange-400"
+          value={n}
+          bind:group={rating}
+          readonly
+          disabled
+        />
+    {/each}
+  </div>
+</label>
```
Comment (CallumHoward) [inline apps/web/src/components/StarRating.svelte:21]: Probably this is just because the formatter was run that this shows up in the diff

File: apps/web/src/routes/contact-form-action.ts [hunk 3]
```diff
@@ -2,12 +2,6 @@ import { sendMail } from "$lib/server/email/email";
 import { getErrorMessage } from "$lib/utils/error";
 import { fail } from "@sveltejs/kit";
 
-type Data = {
-  success: boolean;
-  errors: Record<string, string>;
-  missing?: string[];
-};
```
Comment (CallumHoward) [inline apps/web/src/routes/contact-form-action.ts:9]: This was not used

File: apps/studio/schemas/testimonial.ts (hunk 1 above)
Comment (tekhuynh) [reply apps/studio/schemas/testimonial.ts:38]: It is needed or else the generated schema will expect either number or null, instead of just number. By limiting to just numbers, we are able to benefit from the strong typing which simplifies implementation.

File: apps/web/src/lib/sanity/generated-types.ts [hunk 4]
```diff
@@ -124,7 +124,7 @@ export type Testimonial = {
     crop?: SanityImageCrop;
     _type: "image";
   };
-  rating?: number;
```
Comment (tekhuynh) [inline apps/web/src/lib/sanity/generated-types.ts:127]: The .required from the previous comment removes this maybe type, or whatever it's called. I believe it, while not enforced via JavaScript I think, is a hint to the developer that they should handle the null case. It helps prevent those null reference errors we used to get from fuck knows where possible causing the server to repeatedly error and filling up the log server with stack traces and triggering a bunch of server provisioning alarms. Fond mementoes of the mass micro-services hype migration days when php was still relevant. 🤓💩

**Review by tekhuynh — APPROVED** [review]
Good work Callum. You have a gift for... working.

File: apps/web/src/components/StarRating.svelte (hunk 2 above)
Comment (tekhuynh) [reply apps/web/src/components/StarRating.svelte:21]: I changed the variable "number" to n, and we had to put the label on the outside to fix something which enabled the stars to actually render its intended rating I think.
